<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 4.1.2 Linear Regression

In Lab 4.1.1 we were able to predict house price via a predictor variable from first principles. Here we the see how the same can be done using scikit-learn.

For comparison purposes, we will continue with the same predictor `sq__ft` in our dataset as last time.

## Prediction of House Price Using Linear Regression

### Data

The Sacramento real estate transactions file is a list of 985 real estate transactions in the Sacramento area reported over a five-day period, as reported by the Sacramento Bee.

In [23]:
import pandas as pd
import numpy as np
import math
import seaborn as sns
import pandas as pd

from scipy import stats
from matplotlib import pyplot as plt

%matplotlib inline

### 1. Read in the data

In [24]:
# Read CSV
path = r'C:\Users\Vinitha\Desktop\IOD\DATA\Sacramento_transactions.csv'
#house_csv = "Sacramento_transactions.csv"
data = pd.read_csv(path)
data.head()

street        city    zip state  beds  baths  sq__ft  \
0      3526 HIGH ST  SACRAMENTO  95838    CA     2      1     836   
1       51 OMAHA CT  SACRAMENTO  95823    CA     3      1    1167   
2    2796 BRANCH ST  SACRAMENTO  95815    CA     2      1     796   
3  2805 JANETTE WAY  SACRAMENTO  95815    CA     2      1     852   
4   6001 MCMAHON DR  SACRAMENTO  95824    CA     2      1     797   

          type                     sale_date  price   latitude   longitude  
0  Residential  Wed May 21 00:00:00 EDT 2008  59222  38.631913 -121.434879  
1  Residential  Wed May 21 00:00:00 EDT 2008  68212  38.478902 -121.431028  
2  Residential  Wed May 21 00:00:00 EDT 2008  68880  38.618305 -121.443839  
3  Residential  Wed May 21 00:00:00 EDT 2008  69307  38.616835 -121.439146  
4  Residential  Wed May 21 00:00:00 EDT 2008  81900  38.519470 -121.435768

In [25]:
data.describe()

zip        beds       baths       sq__ft          price  \
count    985.000000  985.000000  985.000000   985.000000     985.000000   
mean   95750.697462    2.911675    1.776650  1314.916751  234144.263959   
std       85.176072    1.307932    0.895371   853.048243  138365.839085   
min    95603.000000    0.000000    0.000000     0.000000    1551.000000   
25%    95660.000000    2.000000    1.000000   952.000000  145000.000000   
50%    95762.000000    3.000000    2.000000  1304.000000  213750.000000   
75%    95828.000000    4.000000    2.000000  1718.000000  300000.000000   
max    95864.000000    8.000000    5.000000  5822.000000  884790.000000   

         latitude   longitude  
count  985.000000  985.000000  
mean    38.607732 -121.355982  
std      0.145433    0.138278  
min     38.241514 -121.551704  
25%     38.482717 -121.446127  
50%     38.626582 -121.376220  
75%     38.695589 -121.295778  
max     39.020808 -120.597599

In [26]:
data[['price', 'sq__ft', 'beds']].describe()

price       sq__ft        beds
count     985.000000   985.000000  985.000000
mean   234144.263959  1314.916751    2.911675
std    138365.839085   853.048243    1.307932
min      1551.000000     0.000000    0.000000
25%    145000.000000   952.000000    2.000000
50%    213750.000000  1304.000000    3.000000
75%    300000.000000  1718.000000    4.000000
max    884790.000000  5822.000000    8.000000

In [27]:
!pip install scikit-learn

# import the LinearRegression class from the sklearn.linear_model module
from sklearn.linear_model import LinearRegression

In [28]:
data[['price', 'sq__ft', 'beds']].describe()

price       sq__ft        beds
count     985.000000   985.000000  985.000000
mean   234144.263959  1314.916751    2.911675
std    138365.839085   853.048243    1.307932
min      1551.000000     0.000000    0.000000
25%    145000.000000   952.000000    2.000000
50%    213750.000000  1304.000000    3.000000
75%    300000.000000  1718.000000    4.000000
max    884790.000000  5822.000000    8.000000

In [31]:
#data['beds'].quantile(0.25)
#data.boxplot('beds')

In [22]:
#Q1 = data[['price', 'sq__ft', 'beds']].quantile(0.25)
#Q3 = data[['price', 'sq__ft', 'beds']].quantile(0.75)
#IQR = Q3 - Q1
#lower_bound = Q1 - 1.5 * IQR
#upper_bound = Q3 + 1.5 * IQR
# Filter out the outliers
#data_no_outliers = data[(data[['price', 'sq__ft', 'beds']] >= lower_bound) & (data[['price', 'sq__ft', 'beds']] <= upper_bound)]

In [32]:
#print(f'The stats with outliers: \n {data[['price', 'sq__ft', 'beds']].describe()}')
#print(f'\n The stats without outliers: \n {data_no_outliers[['price', 'sq__ft', 'beds']].describe()}')

In [33]:
data['city'].value_counts()

city
SACRAMENTO         439
ELK GROVE          114
LINCOLN             72
ROSEVILLE           48
CITRUS HEIGHTS      35
ANTELOPE            33
RANCHO CORDOVA      28
EL DORADO HILLS     23
GALT                21
NORTH HIGHLANDS     21
CARMICHAEL          20
FOLSOM              17
ROCKLIN             17
RIO LINDA           13
ORANGEVALE          11
PLACERVILLE         10
CAMERON PARK         9
FAIR OAKS            9
WILTON               5
AUBURN               5
GOLD RIVER           4
ELVERTA              4
WEST SACRAMENTO      3
RANCHO MURIETA       3
POLLOCK PINES        3
GRANITE BAY          3
LOOMIS               2
EL DORADO            2
MATHER               1
PENRYN               1
MEADOW VISTA         1
FORESTHILL           1
DIAMOND SPRINGS      1
SHINGLE SPRINGS      1
COOL                 1
WALNUT GROVE         1
GARDEN VALLEY        1
SLOUGHHOUSE          1
GREENWOOD            1
Name: count, dtype: int64

In [46]:
!pip install scikit-learn

# import the LinearRegression class from the sklearn.linear_model module
from sklearn.linear_model import LinearRegression

### 2. Predict Price

We are going to predict the target variable `price` from `sq__ft` using sklearn's linear_model.

Read up on the following methods and attributes here: [sklearn.linear_model.LinearRegression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html)

- coef_
- intercept_
- fit()
- predict()
- score()

#### 2.1 Create an instance of LinearRegression.

In [59]:
#X = np.array([[1], [2], [3], [4], [5]])  # Example feature 'beds'
#y = np.array([100, 150, 200, 250, 300])  # Example target 'price'

linreg = LinearRegression()

linreg.fit(X, y)

LinearRegression()

In [60]:
# Identify outliers using the IQR method
#Q1 = data[['price', 'sq__ft', 'beds']].quantile(0.25)
#Q3 = data[['price', 'sq__ft', 'beds']].quantile(0.75)

#### 2.2 Fit predictor and target variables using linear regression

In [61]:
# ANSWER
X = data['sq__ft'].values.reshape(-1,1)
y = data['price']

#### 2.3. Using attributes of the LinearRegression() class find coefficient and intercept.

In [62]:
print('coef: ',linreg.coef_ , 'intercept: ', linreg.intercept_)

coef:  [54.15863969] intercept:  162930.16140699777


#### 2.4 Find R^2 Score

Find $R^2$ Using the ```score``` method of LinearRegression.

In [63]:
# ANSWER
linreg.score(X, y)

0.11148717682951437

### 3. Splitting Data


Splitting the data into training and test sets is important in supervised learning.

- We ensure that the test set remains untouched during the model training process. This isolation prevents any information leakage about the test set into the training process.

- It allows us to evaluate the performance of our machine learning model on unseen data.


In [64]:
from sklearn.model_selection import train_test_split

#### 3.1 Create training and testing subsets

Hint: Use the `train_test_split` Library.

```
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
```

In [72]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [68]:
# ANSWER
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
## Create training and testing subsets
train = linreg.fit(X_train, y_train)

print("Coefficients:", train.coef_)
print("Intercept:", train.intercept_)

Coefficients: [47.43508406]
Intercept: 166482.3414496886


#### 3.2 Check Shape, Sample of Test Train Data

In [69]:
print('X_train is a %s' % type(X_train))
print('X_train has %d rows', X_train.shape[0])
print('')
print('Sample of X_train%s' % ('_'*50))
print(X_train[:10])

print('')
print('y_train is a %s' % type(y_train))
print('y_train has %d rows', y_train.shape)
print('')
print('Sample of y_train%s' % ('_'*50))
print(y_train[:10])

X_train is a <class 'numpy.ndarray'>
X_train has %d rows 659

Sample of X_train__________________________________________________
[[1758]
 [1643]
 [2354]
 [   0]
 [1354]
 [   0]
 [ 958]
 [1232]
 [ 888]
 [1440]]

y_train is a <class 'pandas.core.series.Series'>
y_train has %d rows (659,)

Sample of y_train__________________________________________________
433    217500
172     99000
125    335750
541    488750
879    104000
888    119000
90     244960
924    170000
181    125000
274    292000
Name: price, dtype: int64


In [70]:
# About test
print('X_train is a %s' % type(X_test))
print('X_train has %d rows', X_test.shape)
print('')
print('Sample of X_train%s' % ('_'*50))
print(X_test[:10])

print('')
print('y_train is a %s' % type(y_test))
print('y_train has %d rows', y_test.shape)
print('')
print('Sample of y_train%s' % ('_'*50))
print(y_test[:10])

X_train is a <class 'numpy.ndarray'>
X_train has %d rows (326, 1)

Sample of X_train__________________________________________________
[[ 906]
 [2382]
 [1962]
 [1739]
 [1527]
 [   0]
 [   0]
 [1900]
 [   0]
 [   0]]

y_train is a <class 'pandas.core.series.Series'>
y_train has %d rows (326,)

Sample of y_train__________________________________________________
613     77000
451    236000
731    240971
436    221000
275    293993
582      4897
707    215000
299    361745
718    222500
494    307000
Name: price, dtype: int64


In [147]:
# ANSWER  .values.reshape(-1,1 X = data['sq__ft'].values.reshape(-1,1)
# Make predictions on the testing set
y_pred = linreg.predict(X_test)
test = data['sq__ft'].values.reshape(-1,1)
# Print predictions and actual values
print("First 5 Predicted values:", y_pred[:5])
print("Actual values:", y_test)
# Evaluate the model using the score method
score = linreg.score(X_test, y_test)
print("R^2 Score (model performance):", score)
## Check training/test data

First 5 Predicted values: [209458.52761247 279472.71169224 259549.97638499 248971.95263852
 238915.71481676]
Actual values: 613     77000
451    236000
731    240971
436    221000
275    293993
        ...  
697    205000
797    325000
328    572500
525    408431
971    224000
Name: price, Length: 326, dtype: int64
R^2 Score (model performance): 0.13602012247180006


#### 3.3 Using Linear Regression Find The Score

1. Fit model using X_train, y_train
2. Find score using X_test, y_test

In [73]:
linreg = LinearRegression()
linreg.fit(X_train, y_train)

print(linreg.coef_, linreg.intercept_)

[47.43508406] 166482.3414496886


In [74]:
linreg.score(X_test, y_test)

0.13602012247180006

### 4. Predict House Price

Let's assume we have information of following house:

- street:	1140 EDMONTON DR
- city:	SACRAMENTO
- zip:	95833
- state:	CA
- beds:	3
- baths:	2
- sq__ft:	1204
- type:	Residential

**Predict the price of this house using the linear regression model.**

In [77]:
# ANSWER
linreg.intercept_, linreg.coef_
beta0 = linreg.intercept_
beta1 = linreg.coef_
x = 1204

Ypred = beta1 * x + beta0
print('Predicted house price: ', Ypred[0])

Predicted house price:  223594.18266380776


In [78]:
x = [[1204]]
Ypred = linreg.predict(x)
print('Predicted house price: ', Ypred[0])

Predicted house price:  223594.18266380776


#### Find the error

In [80]:
# Predict price from X_test
y_preds = linreg.predict(X_test)
y_preds[:10]

array([209458.52761247, 279472.71169224, 259549.97638499, 248971.95263852,
       238915.71481676, 166482.34144969, 166482.34144969, 256609.00117297,
       166482.34144969, 166482.34144969])

In [85]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_preds, squared=True)

C:\Users\Vinitha\anaconda3\envs\IOD\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


18951801967.76203

### Conclusion
We have seen that through scikit-learn, minimal code is needed to implement and evaluate a linear regression model.



---



---



> > > > > > > > > © 2024 Institute of Data


---



---



